### ISSUE TITLE
ReadME.md datei unvollständig

### ISSUE THREAD

**Issue by DavidImmanuelSchwieder** [Niklas574/Docker#1]
Sehr Geehrter Herr Niklas,
Sie haben in ihrer ReadME.md Datei aus dem Docker repository eine sehr wichtige frage vergessen zu beantworten.
Die Frage die sie vergessen haben ist folgende:
Wie können Docker-Images mit Tags versehen werden, und wozu dienen diese Tags? 
Ich hoffe das sie ihre ReadME.md Datei überarbeiten 
Mit Freundlichen Grüßen
David von Schwieder

**Comment by Niklas574** [comment]
Guten Tag @DavidImmanuelSchwieder,
Wenn du wissen möchtest wie Tags erstellt werden kannst du hier nachschauen:
https://github.com/Niklas574/Docker/blob/main/Übungsaufgaben/Aufgabe1/Commands.md
Und zur zweiten Frage wozu tags dienen:
https://kodekloud.com/blog/docker-image-tag/
